version: '1.0'
services:
  frontend:
    build:
      context: frontend
      dockerfile: ./Dockerfile
    ports:
      - "5173:5173"
  backend:
    build:
      context: backend
      dockerfile: ./Dockerfile
    ports:
      - "1337:8080"
  web:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/dist:/usr/share/nginx/html
    ports:
      - "80:80"
