name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      with:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}

    - name: Get current date # get the date of the build
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d--%M-%S')"
    
    - name: Build and push image
      uses: docker/build-push-action@v5
      with:
          context: .
          platforms: linux/amd64,linux/arm/v7
          push: true
          tags: rauraurautis/moviereviews-frontend:latest
          
     # run: |
      #  docker buildx build --platform linux/amd64,linux/arm/v7 -t rauraurautis/moviereviews-frontend:latest .
       # echo "Current date is ${{steps.date.outputs.date}}, set it as tag for docker image!"
    
   # - name: Push image
    #  run: docker push rauraurautis/moviereviews-frontend:latest
   
