name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install frontend dependencies and build
        run: |
          cd frontend
          npm install
          npm run build

      - name: Move frontend build to backend
        run: |
          mv frontend/dist backend/

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t rauraurautis/pirkkaletterboxd:latest backend/.
          docker push rauraurautis/pirkkaletterboxd:latest
